### PR TITLE
Added Osram Plug and extra isNaN Check on state values.

### PR DESCRIPTION
**Pull request by steffjenl**
added support for osram plugs and because the osram plugs don't have bri state i have created an extra check with isNaN because the Osram Plug the bri value is NaN (null).

### CODE REVIEW

**Comment by SkorpionNL** [comment]
Can this PR be merged with master? @WeeJeWel

**Comment by WeeJeWel** [comment]
Could you split this PR into:

1. Fix Osram lightify missing bri parameter
2. Adds support for Socket plugs

**Comment by steffjenl** [comment]
> Could you split this PR into:
> 
> 1. Fix Osram lightify missing bri parameter
> 2. Adds support for Socket plugs

1. "Fix Osram lightify missing bri parameter" i don't change any bri parameter? i only add support socket support.

**Comment by steffjenl** [comment]
> Could you split this PR into:
> 
> 1. Fix Osram lightify missing bri parameter
> 2. Adds support for Socket plugs

You want an PR for "if( convertedValue === null ||  isNaN(convertedValue) === true) continue;" ?

**Comment by WeeJeWel** [comment]
Yes please!

**Comment by steffjenl** [comment]
> Yes please!

@WeeJeWel #117 and #118

**Pull request closed without merging**
