### PR TITLE
Add enable/disable motionsensor flow cards and battery status for dimmer and tap

### PR DESCRIPTION
**Pull request by denniedegroot**

### CODE REVIEW

**Comment by denniedegroot** [comment]
I also changed the motionsensor images to match the images of the other devices in the app store.

**Comment by denniedegroot** [comment]
I also added the battery status of the dimmer and tap.

Note that I changed their driver class to sensor to enable the flow cards and to show the battery status in the device cards.

**Comment by caseda** [comment]
does measure_battery work for the TAP? since the tap has no battery whatsoever.

**Comment by denniedegroot** [comment]
Didn't think of that! Huejay exposes battery for every switch but it is indeed not needed for the tap.

**Pull request closed without merging**
